config/routes.rb
StockApp::Application.routes.draw do
  get "stocks/new"

  root to: 'static_pages#home'
  
  resources 'stocks' 

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  attr_accessible :name, :ticker, :url

  def roe_growth?
    roe_before_last > roe_fourth_year && roe_last_year > roe_before_last  ? true : false
  end

  def eps_growth?
    eps_growth1 > eps_growth2 && eps_growth2 > eps_growth3 && eps_growth3 > eps_growth4  ? true : false
  end

  def eps_growth_lq?
  	eps_growth1 > eps_growth2 ? true : false
  end

  def eps_growth_2q?
  	eps_growth2 > eps_growth3 ? true : false
  end

  def eps_growth_3q?
  	eps_growth3 > eps_growth4 ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/stocks_controller.rb
require 'nokogiri'
require 'open-uri'

class StocksController < ApplicationController
  
  def index
  	@stocks = Stock.all
  end

  def new
  	@stock = Stock.new
  end

  def create
  	@stock = Stock.create(params[:stock])
  	stock_data_retriever
    eps_growth

  	if @stock.save 
  	  redirect_to stocks_path
  	else
  	  render :edit
  	end
  end

  def stock_data_retriever
  	url = "http://www.nasdaq.com/symbol/#{@stock.ticker}/financials?query=ratios"
    doc = Nokogiri::HTML(open(url))
    @stock.roe = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 12) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 3) and parent::*)]').text
    @stock.roe_last_year = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 12) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 4) and parent::*)]').text
    @stock.roe_before_last = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 12) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 5) and parent::*)]').text
    @stock.roe_fourth_year = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 12) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 6) and parent::*)]').text

    @stock.roe = @stock.roe.to_int
    @stock.roe_last_year = @stock.roe_last_year.to_int
    @stock.roe_before_last = @stock.roe_before_last.to_int
    @stock.roe_fourth_year = @stock.roe_fourth_year.to_int
  end

  def eps_growth
    url = "http://www.nasdaq.com/earnings/report/#{@stock.ticker}"
    doc = Nokogiri::HTML(open(url))
    @stock.eps_growth1 = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 3) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 3) and parent::*)]').text
    @stock.eps_growth2 = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 4) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 3) and parent::*)]').text
    @stock.eps_growth3 = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 5) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 3) and parent::*)]').text
    @stock.eps_growth4 = doc.xpath('//tr[(((count(preceding-sibling::*) + 1) = 6) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 3) and parent::*)]').text
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
	<%= "Stock App" %>
      <nav>
	    <ul class="nav pull-right">
        <li><%= link_to "Home", root_path %></li>
  		  <li><%= link_to "Stock Data", stocks_path %></li>
  		  <li><%= link_to "Add Data", stocks_new_path %></li>
      </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>Home Page </h1>

app/views/stocks/_form.html.erb
<%= form_for @stock do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :ticker %>
  <%= f.text_field :ticker %><br />
  <%= f.submit %>
<% end %>

app/views/stocks/_stock_summary.html.erb
<table class="table table-bordered">
  <caption>Return on Equity</caption>
  <thead>
  <tr>
  	<th>Name</th>
  	<th>Ticker</th>
    <th>ROE</th>
    <th>ROE last year</th>
    <th>ROE before last</th>
    <th>ROE four years ago</th>
    <th>EPS 4 quarters ago</th>
    <th>EPS 3 quarters ago</th>
    <th>EPS 2 quarters ago</th>
    <th>EPS 1 quarters ago</th>
  <tr>
  </thead>
  <tbody>
  <% @stocks.each do |stock| %>
  <tr>
	  <td><%= stock.name %></td>
    <td><%= stock.ticker %></td>
    <td><%= stock.roe %></td>
    <td><%= stock.roe_last_year %></td>
    <td><%= stock.roe_before_last %></td>
    <td><%= stock.roe_fourth_year %></td>
    <td class="<%= stock.eps_growth_lq? ? 'rowGreen' : 'rowRed' %>"><%= stock.eps_growth1 %></td>
    <td class="<%= stock.eps_growth_2q? ? 'rowGreen' : 'rowRed' %>"><%= stock.eps_growth2 %></td>
    <td class="<%= stock.eps_growth_3q? ? 'rowGreen' : 'rowRed' %>"><%= stock.eps_growth3 %></td>
    <td><%= stock.eps_growth4 %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/stocks/index.html.erb
<% provide(:title) %>
<h1>Stocks</h1>
<%= render partial: 'stock_summary' %>

app/views/stocks/new.html.erb
<% provide(:title, 'Add data') %>
<h1>Add Stock Data</h1>
<%= render partial: 'form' %>